logging:
  level:
    root: INFO
    '[org.springframework]': info
    '[org.springframework.cloud.gateway]': debug
    '[org.springframework.security.oauth2]': debug
spring:
  security:
    oauth2:
      client:
        registration:
          cas:
            client-id: external-oauth2
            client-secret: aaaa
            authorization-grant-type: implicit
            redirect-uri: "{baseUrl}/authorized/cas"
        provider:
          cas:
            authorization-uri: https://dev.geo2france.fr/cas/oauth2.0/authorize
            token-uri: https://dev.geo2france.fr/cas/oauth2.0/token
            user-info-uri: https://dev.geo2france.fr/cas/oauth2.0/introspect
